version: "3.7"

services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Montevideo
    volumes:
      - /home/${USER}/server/configs/qbittorrent:/config
      - /media/TwoTOne/data/Torrents:/dataOne/Torrents/
      - /media/TwoTTwo/data/Torrents:/dataTwo/Torrents/
      - /media/OneTOne/data/torrents:/dataThree/torrents/
      - /media/FourTOne/data/Torrents:/dataFour/Torrents
    restart: unless-stopped
