version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - type: bind
        source: /home/${USER}/server/configs/komga
        target: /config
      - type: bind
        source: /media/OneTOne/Reads/
        target: /data
    ports:
      - 25600:25600
    user: "1000:1000"
    environment:
      - TZ=America/Montevideo
      - KOMGA_LIBRARIES_SCAN_CRON=0 */15 * * * ?
    restart: unless-stopped
