version: '3'
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - "/home/${USER}/server/configs/jdownloader-2:/config:rw"
      - "/media/OneTOne/data/downloads:/downloads:rw"
