version: "2"

services:
  app:
    image: containrrr/watchtower
    hostname: Watcher
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Montevideo
      - NO_COLOR=true
      - WATCHTOWER_SCHEDULE=0 0 23 * * *
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_MONITOR_ONLY=false
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=
      - WATCHTOWER_NOTIFICATION_GOTIFY_TLS_SKIP_VERIFY=true
