version: '2.2'
services:
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/yrvn/server/configs/nginx/data:/data
      - /home/yrvn/server/configs/nginx/letsencrypt:/etc/letsencrypt
