version: "2.1"
services:
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montevideo
    volumes:
      - /home/${USER}/server/configs/mylar3:/config
      - /media/OneTOne/Reads/Comics:/comics
      - /media/OneTOne/data:/data
    ports:
      - 8090:8090
    restart: unless-stopped
